### ISSUE TITLE
HTTPS error: SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by fliermanrw** [api-postcode/php-client#1]
When trying to get a postcode result from the api, when using httpS instead of http it results in the following error:

```
Error: SSL peer certificate or SSHremote key was not OK
```

Is this a bug or is it on purpose you cannot connect over https instead of http?

If you need additional information please let me know!

**Comment by dam-man** [comment]
The server is not accepting SSL indeed. Can this be added to the API? Perhaps a free Let's encrypt certificate

**Comment by Shivella** [comment]
The API is now using HTTPS.
