### ISSUE TITLE
php-client werkt niet zonder meer

### ISSUE THREAD

**Issue by idsosd** [api-postcode/php-client#2]
Ik ben docent webdevelopment en met mijn studenten heb ik geprobeerd deze API aan de praat te krijgen. Dat lukt op zich, maar niet zonder meer: we moesten de verwijzingen naar verschillende classes zelf toevoegen. Ook als we api-postcode via composer installeren, werkt het niet meteen. Onze vraag is: missen we nog een detail waardoor het niet zonder meer werkt, of is het toch een bug? We zijn heel benieuwd.

**Comment by Shivella** [comment]
Hey, kan je mij wat meer details geven waarom het niet werkt? 
Eventueel een error of voorbeeld van de code?

De package zou moeten werken, ik gebruik hem zelf in verschillende live projecten en ook op https://www.api-postcode.nl wordt de package gebruikt in de footer voor de online status.
