### ISSUE TITLE
Accessing json.api-postcode.nl from a web client

### ISSUE THREAD

**Issue by commonpike** [api-postcode/php-client#4]
This isn't the right place to post this issue, but I don't know where else to do it.

is using the api (with an API key) from a browser a supported use case ? 

I registered for a key and tried to build a Vue component to access the API, but ran into a silly problem:

 - The API requires the Token to be in the http headers
 - this causes the browser to send a preflight (OPTIONS) request
 - the server doesn't respond with a CORS `Access-Control-Allow-Origin:* ` on the preflight request
 - the preflight request fails and so the client fails
 
That seems simple enough to fix, but I don't know if you want to allow browsers to access the API like this at all, perhaps this is by design.

**Comment by Shivella** [comment]
Hey!

You have to implement the API in your backend / server side instead of client side.
Implementing the API on client side will also publicly expose your API key.

So this is by design.

Gr!
